---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-self-signed
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  isCA: true
  duration: 80640h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-self-signed
    kind: ClusterIssuer
  secretName: linkerd-trust-anchor
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-webhook-issuer
  namespace: cert-manager
spec:
  isCA: true
  duration: 80640h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-self-signed
    kind: ClusterIssuer
  secretName: linkerd-webhook-issuer
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  commonName: webhook.linkerd.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-trust-anchor

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-webhook-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-webhook-issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: cert-manager
spec:
  secretName: linkerd-identity-issuer
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 80640h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth

---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  namespace: cert-manager
spec:
  sources:
    - secret:
        name: linkerd-identity-issuer
        key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 72576h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 72576h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
    - linkerd-policy-validator.linkerd.svc
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - server auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 72576h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
    - linkerd-proxy-injector.linkerd.svc
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - server auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 72576h
  renewBeforePercentage: 25
  issuerRef:
    name: linkerd-webhook-issuer
    kind: ClusterIssuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
    - linkerd-sp-validator.linkerd.svc
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - server auth
