ingress:
  enabled: true
  className: "traefik-linkerd"
  hosts:
    - host: &host podinfo-linkerd.k8sj.io
      paths:
        - path: /
          pathType: ImplementationSpecific

nodeSelector:
  topology.kubernetes.io/zone: m

#  tls:
#    - hosts:
#        - *host
#      secretName: podinfo-tls
