---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crt.yaml
  - ./prom-policy.yaml

helmCharts:
  - name: linkerd-viz
    repo: https://helm.linkerd.io/stable
    version: 30.12.11
    releaseName: linkerd-viz
    includeCRDs: true
    namespace: linkerd-viz
    valuesFile: values.yaml
