---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: "6.9.1"
    releaseName: podinfo
    includeCRDs: true
    namespace: podinfotest
    valuesFile: ./../../../../base/podinfotest/podinfo2/values.yaml
    additionalValuesFiles:
      - ./values.yaml
