deployment:
  podAnnotations:
    linkerd.io/inject: ingress
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-linkerd
providers:
  kubernetesIngress:
    publishedService:
      enabled: true

nodeSelector:
  topology.kubernetes.io/zone: m

logs:
  access:
    enabled: true
ports:
  traefik:
    expose:
      default: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: ["web"]
