apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-test
  annotations:
    config.linkerd.io/proxy-await: "enabled"
    linkerd.io/inject: "enabled"
    config.linkerd.io/default-inbound-policy: "cluster-authenticated"

