name: Kustomize Diff

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  diff:
    name: Kustomize Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get list of changed directories
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Find affected kustomizations
        id: kustomizations
        run: |
          KUSTOMIZATIONS=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomizations=$KUSTOMIZATIONS" >> "$GITHUB_OUTPUT"
          echo "Affected kustomizations: $KUSTOMIZATIONS"

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
          fetch-depth: 0

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Generate diffs
        id: generate-diff
        run: |
          mkdir -p manifests/base manifests/pr
          for path in ${{ steps.kustomizations.outputs.kustomizations }}; do
            BASENAME=$(basename "$path")
            echo "Building manifests for $path"
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone base-branch/$path > manifests/base/$BASENAME.yaml
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone $path > manifests/pr/$BASENAME.yaml
          done

          COMMENT_FILE=diff-comment.md

          set +e
          diff=$(git diff --no-index --color=never manifests/base manifests/pr 2>&1)
          diff_exit_code=$?
          set -e

          # Check exit code and prepare output accordingly
          if [[ $diff_exit_code -eq 0 ]]; then
            output="No differences found in kustomize output after merging $GITHUB_HEAD_REF into $GITHUB_BASE_REF"
          else
            # Wrap diff in markdown code block for proper formatting
            output="\`\`\`diff\n${diff}\n\`\`\`"
          fi

          # Escape newlines for GitHub Actions output
          escaped_output="${output//$'\n'/'%0A'}"

          # Truncate if the comment is too large
          if [ ${#escaped_output} -gt 65000 ]; then
            escaped_output="Output is greater than 65000 characters, and therefore too large to print as a GitHub comment."
          fi

          # Write to step output
          echo "comment=$escaped_output" >> $GITHUB_OUTPUT

      - name: Post Sticky PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.generate-diff.outputs.comment }}
          header: "### :gear: Kustomize Diff"
