name: Kustomize Diff

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  diff:
    name: Kustomize Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get list of changed directories
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Find affected kustomizations
        id: kustomizations
        run: |
          kustomizations=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomizations=$kustomizations" >> "$GITHUB_OUTPUT"
          echo "Affected kustomizations: $kustomizations"

      - name: Checkout base branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
          fetch-depth: 0

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.7.1"


      - name: Generate diffs
        id: diff
        run: |
          DIFF_CONTENT=""
          for path in ${{ steps.kustomizations.outputs.kustomizations }}; do
            echo "Building manifests for $path"

            TMPDIR=.$(mktemp -d)
            clean_path="${path#./}"

            mkdir -p $TMPDIR/$clean_path
            mkdir -p $TMPDIR/{base,pr}/$clean_path

            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone base-branch/$path -o $TMPDIR/base/$clean_path
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone $path -o $TMPDIR/pr/$clean_path

            TMP_DIFF_FILE="$TMPDIR/$clean_path/diff.txt"

            # Capture git diff without exiting on differences
            set +e
            git diff --no-index --color=never $TMPDIR/base/$clean_path $TMPDIR/pr/$clean_path > $TMP_DIFF_FILE 2>&1
            exit_code=$?
            set -e

            # Fallback message if no changes
            if [[ $exit_code -eq 0 ]]; then
              DIFF_CONTENT+="# $path\nNo differences found\n\n"
            else
              DIFF_CONTENT+="# $path\n\n"
              DIFF_CONTENT+="\`\`\`diff\n$(cat $TMP_DIFF_FILE)\n\`\`\`\n\n"
            fi
          done

          # Export diff as GitHub Actions output
          echo "comment<<EOF" >> "$GITHUB_OUTPUT"
          echo -e "$DIFF_CONTENT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"

      - name: Post PR Comment (update existing)
        if: ${{ steps.diff.outputs.comment != '' }}
        uses: actions/github-script@v8
        env:
          DIFF_COMMENT: ${{ steps.diff.outputs.comment }}
        with:
          script: |
            const marker = "<!-- diff-comment -->";
            const diffComment = process.env.DIFF_COMMENT;
            const commentBody = marker + "\n" + diffComment;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.find(c => c.body.includes(marker));

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }
