name: Kustomize Diff

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  diff:
    name: Kustomize Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get list of changed directories
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Find affected kustomizations
        id: kustomizations
        run: |
          kustomizations=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomizations=$kustomizations" >> "$GITHUB_OUTPUT"
          echo "Affected kustomizations: $kustomizations"

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
          fetch-depth: 0


      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- "$KUSTOMIZE_VERSION"
        env:
          KUSTOMIZE_VERSION: "5.7.1"

      - name: Generate diffs
        id: generate-diff
        run: |
          TMPDIR=$(mktemp -d)
          mkdir -p $TMPDIR/base $TMPDIR/pr

          for path in ${{ steps.kustomizations.outputs.kustomizations }}; do
            BASENAME=$(basename "$path")
            echo "Building manifests for $path"
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone base-branch/$path > $TMPDIR/base/$BASENAME.yaml
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone $path > $TMPDIR/pr/$BASENAME.yaml
          done

          TMP_DIFF_FILE=diff-raw.txt

          # Capture git diff
          git diff --no-index --color=never $TMPDIR/base $TMPDIR/pr > $TMP_DIFF_FILE 2>&1 || true
          exit_code=${PIPESTATUS[0]}

          # Fallback message if no changes
          if [[ $exit_code -eq 0 ]]; then
            echo "No differences found in Kustomize output between base and PR build." > $TMP_DIFF_FILE
          fi

          # Read diff into output variable
          comment=$(cat $TMP_DIFF_FILE)
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$comment" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post PR Comment (update existing)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ```diff
            ${{ steps.generate-diff.outputs.comment }}
            ```
