name: Kustomize Diff

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  diff:
    name: Kustomize Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
          fetch-depth: 0

      - name: Get list of changed directories
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Find affected kustomizations
        id: kustomizations
        run: |
          KUSTOMIZATIONS=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomizations=$KUSTOMIZATIONS" >> "$GITHUB_OUTPUT"
          echo "Affected kustomizations: $KUSTOMIZATIONS"

      - name: Build manifests
        run: |
          mkdir -p manifests/pr manifests/base
          for path in ${{ steps.kustomizations.outputs.kustomizations }}; do
            echo "Building manifests for $path"
            echo "PR"
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone $path
            echo "BASE"
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone base-branch/$path
          done

#      - name: Generate diffs
#        id: generate-diff
#        run: |
#          COMMENT=""
#          echo -e "\033[1;36m=== Kustomize Manifest Diff ===\033[0m"
#          for path in $kustomizations; do
#            FILE=$(basename $path)
#            DIFF_COLOR=$(git diff --no-index --color manifests/base/${FILE}.yaml manifests/pr/${FILE}.yaml || true)
#            DIFF_PLAIN=$(git diff --no-index --color=never manifests/base/${FILE}.yaml manifests/pr/${FILE}.yaml || true)
#            if [[ -n "$DIFF_PLAIN" ]]; then
#              # Show colored diff in Actions log
#              echo -e "\n\033[1;33m--- Diff for $path ---\033[0m"
#              echo -e "$DIFF_COLOR"
#              # Prepare PR comment with diff syntax highlighting
#              COMMENT+="### Diff for \`${path}\`\n\`\`\`diff\n$DIFF_PLAIN\n\`\`\`\n"
#            fi
#          done
#          if [[ -z "$COMMENT" ]]; then
#            COMMENT="No Kustomize changes detected."
#          fi
#          echo "$COMMENT" > diff-comment.md

#      - name: Post Sticky PR Comment
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          path: diff-comment.md
#          header: "### :gear: Kustomize Diff"
