name: Kustomize Diff

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  diff:
    name: Kustomize Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get list of changed directories
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Find affected kustomizations
        id: kustomizations
        run: |
          KUSTOMIZATIONS=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomizations=$KUSTOMIZATIONS" >> "$GITHUB_OUTPUT"
          echo "Affected kustomizations: $KUSTOMIZATIONS"

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
          fetch-depth: 0

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Generate diffs
        id: generate-diff
        run: |
          mkdir -p manifests/base manifests/pr
          for path in ${{ steps.kustomizations.outputs.kustomizations }}; do
            BASENAME=$(basename "$path")
            echo "Building manifests for $path"
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone base-branch/$path > manifests/base/$BASENAME.yaml
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone $path > manifests/pr/$BASENAME.yaml
          done

          set +e
          diff=$(git diff --no-index --color=never manifests/base manifests/pr 2>&1)
          exit_code=$?

          if [[ $exit_code -eq 0 ]]; then
            output="No differences found in Kustomize output between base and PR build."
          else
            # Wrap in diff block for proper formatting
            output="$diff"
          fi

          # Escape newlines for GitHub Actions output
          escaped_output="${output//$'\n'/'%0A'}"

          # Truncate if too long (GitHub has ~65k char limit)
          if [ ${#escaped_output} -gt 65000 ]; then
            escaped_output="Diff output too large to display in a comment."
          fi

          echo "comment=$escaped_output" >> $GITHUB_OUTPUT

      - id: comment
        uses: actions/github-script@v7.1.0
        env:
          OUTPUT: ${{ steps.generate-diff.outputs.comment }}
        with:
          script: |
            const rawOutput = process.env.OUTPUT;
            const noDiffMessage = "No differences found between";

            const formattedOutput = rawOutput.includes(noDiffMessage)
              ? `### ${rawOutput}`
              : `### Kustomize Changes\n<details><summary>Show Diff</summary>\n\n\`\`\`diff\n${rawOutput}\n\`\`\`\n</details>`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: formattedOutput
            })
