name: Find and Process Kustomizations

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  kustomization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get modified folders
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          version: v0.66.0

      - name: Find kustomization folders
        id: find_folders
        run: |
          # Run the script with modified folders as input
          folders=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomization_folders=$folders" >> "$GITHUB_OUTPUT"

      - name: Process kustomization folders
        id: extract_images
        run: |
          declare -A images_set
          for folder in ${{ steps.find_folders.outputs.kustomization_folders }}; do
            echo "Processing folder: $folder"
            mapfile -t imgs < <(kustomize build --enable-helm --load-restrictor LoadRestrictionsNone "$folder" | grep -E 'image: ' | awk '{print $2}')
            for img in "${imgs[@]}"; do
              images_set["$img"]=1
            done
          done

          # Prepare space-separated list of unique images
          printf -v images_str "%s " "${!images_set[@]}"
          images_str="${images_str%" "}"

          echo "docker_images=$images_str" >> "$GITHUB_OUTPUT"


      - name: Scan Docker images
        id: trivy_scan
        run: |
          result=""
          exit_code=0

          for img in ${{ steps.extract_images.outputs.docker_images }}; do
            echo "🔍 Scanning image: $img"

            # Run Trivy JSON scan
            scan_output=$(trivy image --quiet --severity HIGH,CRITICAL --format json "$img" 2>/dev/null) || true

            # Count HIGH and CRITICAL vulnerabilities
            high=$(echo "$scan_output" | jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length')
            critical=$(echo "$scan_output" | jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length')

            # Extract CVE IDs for HIGH/CRITICAL vulnerabilities
            cves=$(echo "$scan_output" | jq -r '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL") | .VulnerabilityID] | unique | join(", ")')

            if [[ $high -eq 0 && $critical -eq 0 ]]; then
              result+="✅ $img → No HIGH/CRITICAL vulnerabilities"$$'\n\n'
            else
              result+="❌ $img → $high HIGH / $critical CRITICAL"$'\n'
              result+="CVE IDs: $cves"$'\n\n'
              exit_code=1
            fi
          done

          # Save outputs for PR comment and final fail
          echo "scan_result<<EOF" >> "$GITHUB_OUTPUT"
          echo "$result" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "trivy_exit_code=$exit_code" >> "$GITHUB_OUTPUT"

      - name: Comment PR with Trivy results
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Trivy Scan Results"
          message: |
            ## 🛡️ Trivy Scan Results
            ${{ steps.trivy_scan.outputs.scan_result }}

      - name: Fail if vulnerabilities found
        if: ${{ steps.trivy_scan.outputs.trivy_exit_code != '0' }}
        run: |
          echo "❌ HIGH or CRITICAL vulnerabilities detected!"
          exit 1
