name: Find and Process Kustomizations

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  kustomization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get modified folders
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          version: v0.61.0

      - name: Find kustomization folders
        id: find_folders
        run: |
          # Run the script with modified folders as input
          folders=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomization_folders=$folders" >> "$GITHUB_OUTPUT"

      - name: Process kustomization folders
        id: extract_images
        run: |
          declare -A images_set
          for folder in ${{ steps.find_folders.outputs.kustomization_folders }}; do
            echo "Processing folder: $folder"
            mapfile -t imgs < <(kustomize build --enable-helm --load-restrictor LoadRestrictionsNone "$folder" | grep -E 'image: ' | awk '{print $2}')
            for img in "${imgs[@]}"; do
              images_set["$img"]=1
            done
          done

          # Prepare space-separated list of unique images
          printf -v images_str "%s " "${!images_set[@]}"
          images_str="${images_str%" "}"

          echo "docker_images=$images_str" >> "$GITHUB_OUTPUT"

      - name: Scan Docker images
        id: trivy_scan
        run: |
          result=""
          for img in ${{ steps.extract_images.outputs.docker_images }}; do
            echo "Scanning image: $img"
            safe_name=$(echo "$img" | sed 's/[:\/]/_/g')
            trivy image --quiet --severity HIGH,CRITICAL --format sarif -o "$safe_name.sarif" "$img"
          done

          jq -s '{runs: map(.runs) | add}' ./*.sarif > trivy.sarif

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
