name: Find and Process Kustomizations

on:
  pull_request:

jobs:
  kustomization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get modified folders
        id: changed
        uses: tj-actions/changed-files@v41
        with:
          dir_names: "true"

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 5.7.1

      - name: Find kustomization folders
        id: find_folders
        run: |
          # Run the script with modified folders as input
          folders=$(./.github/scripts/find_kustomization.sh "${{ steps.changed.outputs.all_changed_files }}")
          echo "kustomization_folders=$folders" >> "$GITHUB_OUTPUT"

      - name: Process kustomization folders
        run: |
          for folder in ${{ steps.find_folders.outputs.kustomization_folders }}; do
            echo "Processing folder: $folder"
            kustomize build "$folder" --enable-helm --load-restrictor LoadRestrictionsNone -o ./tmp/output.yaml

            # - Scan images with Trivy
            # trivy image --input ./tmp/output.yaml
          done
